project_id = "cbulgzclclkbcqjlsvny"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "dual"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false
enable_third_party_auth = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.convert-timezone]
verify_jwt = true

[functions.create-teams-meeting]
verify_jwt = true

[functions.fetch-user-display-names]
verify_jwt = true

[functions.get-user-names]
verify_jwt = true

[functions.security-monitor]
verify_jwt = true

[functions.user-admin]
verify_jwt = true

[edge-runtime]
policy = "oneshot"
inspector_port = 8083