// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://santwetblzwivirmojyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbnR3ZXRibHp3aXZpcm1vanluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTg1MjIsImV4cCI6MjA2ODIzNDUyMn0.sB2CymS3q8zEeQDKQG9pjZX5hdkZZJ6tBmbG1FR92CI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});