// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdcaxygmximfdhnlktrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkY2F4eWdteGltZmRobmxrdHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzU2MzEsImV4cCI6MjA2OTcxMTYzMX0.ldM7jnFut-J8rfoEdURNTqgqouHBvhb6v9ZeD9d8Ais";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});